# Generated by Django 5.2.8 on 2025-11-16 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_remove_taskdetail_assigned_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='is_completed',
        ),
    ]
