# Generated by Django 5.2.8 on 2025-11-16 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_remove_task_is_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='assigned_to',
        ),
    ]
