# Generated by Django 5.2.8 on 2025-11-16 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_task_assigned_to'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
